run:
  timeout: 5m
  tests: false
output:
  sort-results: true
linters:
  disable-all: true
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - wastedassign
issues:
  exclude-rules:
    - text: "G404:" # Ignore weak random number generator lint. We do not need strong randomness here.
      linters:
        - gosec
    - path: _test\.go
      linters:
        - gosec # security is not make sense in tests
